config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'static#home'

  resources :portfolios do
    resources :wallets do
      resources :positions
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :wallets
  has_many :positions, through: :wallets
end

app/models/position.rb
class Position < ApplicationRecord
  enum action: [:buy, :sell]

  belongs_to :wallet
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  has_many :positions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def index
    @portfolios = Portfolio.all
  end

  def show
    @current_portfolio = Portfolio.find(params[:id])
    @wallets = @current_portfolio.wallets
    @positions = @current_portfolio.positions
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  def index
    @wallets = Wallet.where(portfolio_id: params[:portfolio_id])
  end

  def show
    @current_wallet = Wallet.find(params[:id])
    @positions = @current_wallet.positions
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cryptolas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'hello_typescript' %>
  </head>

  <body class="font-sans">
    <%= yield %>
  </body>
</html>

app/views/portfolios/_portfolio_item.html.erb
<div class="portfolio-item">
  <%= link_to portfolio.name, portfolio_path(portfolio) %>
</div>

app/views/portfolios/index.html.erb
<h1>Portfolios</h1>
<hr>
<% @portfolios.each do |portfolio| %>
  <%= render partial: "portfolio_item", locals: { portfolio: portfolio } %>
<% end %>

app/views/portfolios/show.html.erb
<h1><%= @current_portfolio.name %></h1>
<hr>
<div class="positions">
  <% @positions.each do |position| %>
    <%= render partial: "shared/position", locals: { position: position } %>
    <hr>
  <% end %>
</div>

app/views/shared/_position.html.erb
<div class="position-item">
  <div class="position-amount">amount: <%= position.amount %> BTC</div>
  <div class="position-current-value">current: <%= position.current_value %> CHF</div>
  <div class="position-fee-value">fee: <%= position.fee_value %> CHF</div>
  <div class="position-real-value">paid: <%= position.real_value %> CHF</div>
  <div class="position-action"><%= position.action %></div>
  <div class="position-created-at"><%= position.created_at %></div>
  <div class="position-wallet"><%= link_to position.wallet.name, portfolio_wallet_path(position.wallet.portfolio_id, position.wallet.id) %></div>
   
</div>

app/views/wallets/_wallet_item.html.erb
<div class="wallet-item">
  <%= link_to wallet.name, portfolio_wallet_path(wallet.portfolio_id, wallet.id) %>
</div>

app/views/wallets/index.html.erb
<h1>Wallets</h1>
<hr>
<% @wallets.each do |wallet| %>
  <%= render partial: "wallet_item", locals: { wallet: wallet } %>
<% end %>

app/views/wallets/show.html.erb
<h1><%= @current_wallet.name %></h1>
<h2><%= @current_wallet.address %></h2>
<hr>
<div class="positions">
  <% @positions.each do |position| %>
    <%= render partial: "shared/position", locals: { position: position } %>
    <hr>
  <% end %>
</div>